/** Code auto-generated by cOde 1.1.0 **/
#include <R.h> 
 #include <math.h> 

static double parms[5];
static double forc[0];
static double cons[0];
static double range[2];

#define nGridpoints 2 
#define nSplines 0 
#define precision 1e-05 

#define k_AB parms[0] 
 #define k_BC parms[1] 
 #define y0_0 parms[2] 
 #define y1_0 parms[3] 
 #define y2_0 parms[4] 
#define tmin range[0]
#define tmax range[1]


void odemodel_petab_initmod(void (* odeparms)(int *, double *)) {
	 int N=5;
	 odeparms(&N, parms);
}

void odemodel_petab_initforc(void (* odeforcs)(int *, double *)) {
	 int N=0;
	 odeforcs(&N, forc);
}

/** Derivatives (ODE system) **/
void odemodel_petab_derivs (int *n, double *t, double *y, double *ydot, double *RPAR, int *IPAR) {

	 double time = *t;

	 ydot[0] = -1.0*(k_AB*y[0]*1.0);
 	 ydot[1] = 1.0*(k_AB*y[0]*1.0)-1.0*(k_BC*y[1]*1.0);
 	 ydot[2] = 1.0*(k_BC*y[1]*1.0);

}

