/** Code auto-generated by cOde 1.1.0 **/
#include <R.h> 
 #include <math.h> 

static double parms[59];
static double forc[0];
static double cons[0];
static double range[2];

#define nGridpoints 2 
#define nSplines 0 
#define precision 1e-05 

#define Epo parms[0] 
 #define JAK2ActEpo parms[1] 
 #define SOCS3Inh parms[2] 
 #define SOCS3Eqc parms[3] 
 #define JAK2EpoRDeaSHP1 parms[4] 
 #define init_SHP1 parms[5] 
 #define EpoRActJAK2 parms[6] 
 #define EpoRCISInh parms[7] 
 #define EpoRCISRemove parms[8] 
 #define init_EpoRJAK2 parms[9] 
 #define SHP1ActEpoR parms[10] 
 #define SHP1Dea parms[11] 
 #define STAT5ActJAK2 parms[12] 
 #define STAT5ActEpoR parms[13] 
 #define CISInh parms[14] 
 #define CISEqc parms[15] 
 #define STAT5Exp parms[16] 
 #define nuc parms[17] 
 #define cyt parms[18] 
 #define STAT5Imp parms[19] 
 #define CISRNAEqc parms[20] 
 #define CISRNATurn parms[21] 
 #define ActD parms[22] 
 #define init_STAT5 parms[23] 
 #define CISRNADelay parms[24] 
 #define CISTurn parms[25] 
 #define CISEqcOE parms[26] 
 #define CISoe parms[27] 
 #define SOCS3RNAEqc parms[28] 
 #define SOCS3RNATurn parms[29] 
 #define SOCS3RNADelay parms[30] 
 #define SOCS3Turn parms[31] 
 #define SOCS3oe parms[32] 
 #define SOCS3EqcOE parms[33] 
 #define y0_0 parms[34] 
 #define y1_0 parms[35] 
 #define y2_0 parms[36] 
 #define y3_0 parms[37] 
 #define y4_0 parms[38] 
 #define y5_0 parms[39] 
 #define y6_0 parms[40] 
 #define y7_0 parms[41] 
 #define y8_0 parms[42] 
 #define y9_0 parms[43] 
 #define y10_0 parms[44] 
 #define y11_0 parms[45] 
 #define y12_0 parms[46] 
 #define y13_0 parms[47] 
 #define y14_0 parms[48] 
 #define y15_0 parms[49] 
 #define y16_0 parms[50] 
 #define y17_0 parms[51] 
 #define y18_0 parms[52] 
 #define y19_0 parms[53] 
 #define y20_0 parms[54] 
 #define y21_0 parms[55] 
 #define y22_0 parms[56] 
 #define y23_0 parms[57] 
 #define y24_0 parms[58] 
#define tmin range[0]
#define tmax range[1]


void odemodel_Bachmann_MSB2011_initmod(void (* odeparms)(int *, double *)) {
	 int N=59;
	 odeparms(&N, parms);
}

void odemodel_Bachmann_MSB2011_initforc(void (* odeforcs)(int *, double *)) {
	 int N=0;
	 odeforcs(&N, forc);
}

/** Derivatives (ODE system) **/
void odemodel_Bachmann_MSB2011_derivs (int *n, double *t, double *y, double *ydot, double *RPAR, int *IPAR) {

	 double time = *t;

	 ydot[0] = -1.0*(1.0*(Epo*y[0]*JAK2ActEpo/(y[24]*SOCS3Inh/SOCS3Eqc+1.0)))+1.0*(1.0*(y[1]*JAK2EpoRDeaSHP1*y[7]/init_SHP1))+1.0*(1.0*(JAK2EpoRDeaSHP1*y[7]*y[2]/init_SHP1))+1.0*(1.0*(JAK2EpoRDeaSHP1*y[7]*y[3]/init_SHP1))+1.0*(1.0*(JAK2EpoRDeaSHP1*y[7]*y[4]/init_SHP1));
 	 ydot[1] = 1.0*(1.0*(Epo*y[0]*JAK2ActEpo/(y[24]*SOCS3Inh/SOCS3Eqc+1.0)))-1.0*(1.0*(y[1]*JAK2EpoRDeaSHP1*y[7]/init_SHP1))-1.0*(1.0*(y[1]*EpoRActJAK2/(y[24]*SOCS3Inh/SOCS3Eqc+1.0)))-1.0*(1.0*(3.0*y[1]*EpoRActJAK2/((y[24]*SOCS3Inh/SOCS3Eqc+1.0)*(EpoRCISInh*y[5]+1.0))));
 	 ydot[2] = 1.0*(1.0*(y[1]*EpoRActJAK2/(y[24]*SOCS3Inh/SOCS3Eqc+1.0)))-1.0*(1.0*(3.0*EpoRActJAK2*y[2]/((y[24]*SOCS3Inh/SOCS3Eqc+1.0)*(EpoRCISInh*y[5]+1.0))))-1.0*(1.0*(JAK2EpoRDeaSHP1*y[7]*y[2]/init_SHP1));
 	 ydot[3] = 1.0*(1.0*(3.0*y[1]*EpoRActJAK2/((y[24]*SOCS3Inh/SOCS3Eqc+1.0)*(EpoRCISInh*y[5]+1.0))))-1.0*(1.0*(EpoRActJAK2*y[3]/(y[24]*SOCS3Inh/SOCS3Eqc+1.0)))-1.0*(1.0*(JAK2EpoRDeaSHP1*y[7]*y[3]/init_SHP1));
 	 ydot[4] = 1.0*(1.0*(3.0*EpoRActJAK2*y[2]/((y[24]*SOCS3Inh/SOCS3Eqc+1.0)*(EpoRCISInh*y[5]+1.0))))+1.0*(1.0*(EpoRActJAK2*y[3]/(y[24]*SOCS3Inh/SOCS3Eqc+1.0)))-1.0*(1.0*(JAK2EpoRDeaSHP1*y[7]*y[4]/init_SHP1));
 	 ydot[5] = -1.0*(1.0*(y[5]*EpoRCISRemove*(y[4]+y[2])/init_EpoRJAK2));
 	 ydot[6] = -1.0*(1.0*(y[6]*SHP1ActEpoR*(y[1]+y[4]+y[2]+y[3])/init_EpoRJAK2))+1.0*(1.0*SHP1Dea*y[7]);
 	 ydot[7] = 1.0*(1.0*(y[6]*SHP1ActEpoR*(y[1]+y[4]+y[2]+y[3])/init_EpoRJAK2))-1.0*(1.0*SHP1Dea*y[7]);
 	 ydot[8] = -1.0*(1.0*(y[8]*STAT5ActJAK2*(y[1]+y[4]+y[2]+y[3])/(init_EpoRJAK2*(y[24]*SOCS3Inh/SOCS3Eqc+1.0))))-1.0*(1.0*(y[8]*STAT5ActEpoR*(y[4]+pow(y[2],2.0))/((pow(init_EpoRJAK2,2.0))*(y[24]*SOCS3Inh/SOCS3Eqc+1.0)*(y[17]*CISInh/CISEqc+1.0))))+1.0*(1.0*STAT5Exp*y[10])*(nuc/cyt);
 	 ydot[9] = 1.0*(1.0*(y[8]*STAT5ActJAK2*(y[1]+y[4]+y[2]+y[3])/(init_EpoRJAK2*(y[24]*SOCS3Inh/SOCS3Eqc+1.0))))+1.0*(1.0*(y[8]*STAT5ActEpoR*(y[4]+pow(y[2],2.0))/((pow(init_EpoRJAK2,2.0))*(y[24]*SOCS3Inh/SOCS3Eqc+1.0)*(y[17]*CISInh/CISEqc+1.0))))-1.0*(1.0*STAT5Imp*y[9]);
 	 ydot[10] = 1.0*(1.0*STAT5Imp*y[9])*(cyt/nuc)-1.0*(1.0*STAT5Exp*y[10]);
 	 ydot[11] = 1.0*(1.0*(CISRNAEqc*CISRNATurn*y[10]*ActD/init_STAT5))-1.0*(1.0*y[11]*CISRNADelay);
 	 ydot[12] = 1.0*(1.0*y[11]*CISRNADelay)-1.0*(1.0*y[12]*CISRNADelay);
 	 ydot[13] = 1.0*(1.0*y[12]*CISRNADelay)-1.0*(1.0*y[13]*CISRNADelay);
 	 ydot[14] = 1.0*(1.0*y[13]*CISRNADelay)-1.0*(1.0*y[14]*CISRNADelay);
 	 ydot[15] = 1.0*(1.0*y[14]*CISRNADelay)-1.0*(1.0*y[15]*CISRNADelay);
 	 ydot[16] = 1.0*(1.0*y[15]*CISRNADelay)*(nuc/cyt)-1.0*(1.0*y[16]*CISRNATurn);
 	 ydot[17] = 1.0*(1.0*(y[16]*CISEqc*CISTurn/CISRNAEqc))-1.0*(1.0*y[17]*CISTurn)+1.0*(1.0*CISEqc*CISTurn*CISEqcOE*CISoe);
 	 ydot[18] = 1.0*(1.0*(SOCS3RNAEqc*SOCS3RNATurn*y[10]*ActD/init_STAT5))-1.0*(1.0*y[18]*SOCS3RNADelay);
 	 ydot[19] = 1.0*(1.0*y[18]*SOCS3RNADelay)-1.0*(1.0*y[19]*SOCS3RNADelay);
 	 ydot[20] = 1.0*(1.0*y[19]*SOCS3RNADelay)-1.0*(1.0*y[20]*SOCS3RNADelay);
 	 ydot[21] = 1.0*(1.0*y[20]*SOCS3RNADelay)-1.0*(1.0*y[21]*SOCS3RNADelay);
 	 ydot[22] = 1.0*(1.0*y[21]*SOCS3RNADelay)-1.0*(1.0*y[22]*SOCS3RNADelay);
 	 ydot[23] = 1.0*(1.0*y[22]*SOCS3RNADelay)*(nuc/cyt)-1.0*(1.0*y[23]*SOCS3RNATurn);
 	 ydot[24] = 1.0*(1.0*(y[23]*SOCS3Eqc*SOCS3Turn/SOCS3RNAEqc))-1.0*(1.0*y[24]*SOCS3Turn)+1.0*(1.0*SOCS3oe*SOCS3Eqc*SOCS3Turn*SOCS3EqcOE);

}

