/** Code auto-generated by cOde 1.1.0 **/
#include <R.h> 
 #include <math.h> 

static double parms[7];
static double forc[0];
static double cons[0];
static double range[2];

#define nGridpoints 2 
#define nSplines 0 
#define precision 1e-05 

#define k1 parms[0] 
 #define k2 parms[1] 
 #define k3 parms[2] 
 #define y0_0 parms[3] 
 #define y1_0 parms[4] 
 #define y2_0 parms[5] 
 #define y3_0 parms[6] 
#define tmin range[0]
#define tmax range[1]


void odemodel_problem_s_initmod(void (* odeparms)(int *, double *)) {
	 int N=7;
	 odeparms(&N, parms);
}

void odemodel_problem_s_initforc(void (* odeforcs)(int *, double *)) {
	 int N=0;
	 odeforcs(&N, forc);
}

/** Derivatives (ODE system) **/
void odemodel_problem_s_derivs (int *n, double *t, double *y, double *ydot, double *RPAR, int *IPAR) {

	 double time = *t;

	 ydot[0] = 1.0*(1.0*k1/1.0)-1.0*(1.0*k2*y[0]/1.0)-1.0*(1.0*k3*y[0]*y[1]/1.0);
 	 ydot[1] = 1.0*(1.0*k2*y[0]/1.0)-1.0*(1.0*k3*y[0]*y[1]/1.0);
 	 ydot[2] = (-(1.0*k2+1.0*k3*y[1]))*(y[2])+(-(1.0*k3*y[0]))*(y[3])-(y[0]*y[1]);
 	 ydot[3] = (1.0*k2-1.0*k3*y[1])*(y[2])+(-(1.0*k3*y[0]))*(y[3])-(y[0]*y[1]);

}

