/** Code auto-generated by cOde 1.1.0 **/
#include <R.h> 
 #include <math.h> 

static double parms[50];
static double forc[0];
static double cons[0];
static double eventcounter[1];
static double range[2];

#define nGridpoints 2 
#define nSplines 0 
#define precision 1e-05 

#define kproS parms[0] 
 #define kdegS parms[1] 
 #define kon parms[2] 
 #define koff parms[3] 
 #define kcat parms[4] 
 #define Eadd parms[5] 
 #define y0_0 parms[6] 
 #define y1_0 parms[7] 
 #define y2_0 parms[8] 
 #define y3_0 parms[9] 
 #define y4_0 parms[10] 
 #define y5_0 parms[11] 
 #define y6_0 parms[12] 
 #define y7_0 parms[13] 
 #define y8_0 parms[14] 
 #define y9_0 parms[15] 
 #define y10_0 parms[16] 
 #define y11_0 parms[17] 
 #define y12_0 parms[18] 
 #define y13_0 parms[19] 
 #define y14_0 parms[20] 
 #define y15_0 parms[21] 
 #define y16_0 parms[22] 
 #define y17_0 parms[23] 
 #define y18_0 parms[24] 
 #define y19_0 parms[25] 
 #define y20_0 parms[26] 
 #define y21_0 parms[27] 
 #define y22_0 parms[28] 
 #define y23_0 parms[29] 
 #define y24_0 parms[30] 
 #define y25_0 parms[31] 
 #define y26_0 parms[32] 
 #define y27_0 parms[33] 
 #define y28_0 parms[34] 
 #define y29_0 parms[35] 
 #define y30_0 parms[36] 
 #define y31_0 parms[37] 
 #define y32_0 parms[38] 
 #define y33_0 parms[39] 
 #define y34_0 parms[40] 
 #define y35_0 parms[41] 
 #define y36_0 parms[42] 
 #define y37_0 parms[43] 
 #define y38_0 parms[44] 
 #define y39_0 parms[45] 
 #define y40_0 parms[46] 
 #define y41_0 parms[47] 
 #define y42_0 parms[48] 
 #define y43_0 parms[49] 
#define tmin range[0]
#define tmax range[1]


void petab_s_initmod(void (* odeparms)(int *, double *)) {
	 int N=50;
	 odeparms(&N, parms);
	 for(int i=0; i<1; ++i) eventcounter[i] = 0;
}

void petab_s_initforc(void (* odeforcs)(int *, double *)) {
	 int N=0;
	 odeforcs(&N, forc);
}

/** Derivatives (ODE system) **/
void petab_s_derivs (int *n, double *t, double *y, double *ydot, double *RPAR, int *IPAR) {

	 double time = *t;

	 ydot[0] = 1.0*(kproS)-1.0*(kdegS*y[0])-1.0*((kon)*y[1]*y[0])+1.0*(koff*y[2]);
 	 ydot[1] = -1.0*((kon)*y[1]*y[0])+1.0*(koff*y[2])+1.0*(kcat*y[2]);
 	 ydot[2] = 1.0*((kon)*y[1]*y[0])-1.0*(koff*y[2])-1.0*(kcat*y[2]);
 	 ydot[3] = 1.0*(kcat*y[2]);
 	 ydot[4] = (-(kdegS+(kon)*y[1]))*(y[4])+(-((kon)*y[0]))*(y[5])+(koff)*(y[6]);
 	 ydot[5] = (-((kon)*y[1]))*(y[4])+(-((kon)*y[0]))*(y[5])+(koff+kcat)*(y[6]);
 	 ydot[6] = ((kon)*y[1])*(y[4])+((kon)*y[0])*(y[5])+(-(koff+kcat))*(y[6]);
 	 ydot[7] = (kcat)*(y[6]);
 	 ydot[8] = (-(kdegS+(kon)*y[1]))*(y[8])+(-((kon)*y[0]))*(y[9])+(koff)*(y[10]);
 	 ydot[9] = (-((kon)*y[1]))*(y[8])+(-((kon)*y[0]))*(y[9])+(koff+kcat)*(y[10]);
 	 ydot[10] = ((kon)*y[1])*(y[8])+((kon)*y[0])*(y[9])+(-(koff+kcat))*(y[10]);
 	 ydot[11] = (kcat)*(y[10]);
 	 ydot[12] = (-(kdegS+(kon)*y[1]))*(y[12])+(-((kon)*y[0]))*(y[13])+(koff)*(y[14]);
 	 ydot[13] = (-((kon)*y[1]))*(y[12])+(-((kon)*y[0]))*(y[13])+(koff+kcat)*(y[14]);
 	 ydot[14] = ((kon)*y[1])*(y[12])+((kon)*y[0])*(y[13])+(-(koff+kcat))*(y[14]);
 	 ydot[15] = (kcat)*(y[14]);
 	 ydot[16] = (-(kdegS+(kon)*y[1]))*(y[16])+(-((kon)*y[0]))*(y[17])+(koff)*(y[18]);
 	 ydot[17] = (-((kon)*y[1]))*(y[16])+(-((kon)*y[0]))*(y[17])+(koff+kcat)*(y[18]);
 	 ydot[18] = ((kon)*y[1])*(y[16])+((kon)*y[0])*(y[17])+(-(koff+kcat))*(y[18]);
 	 ydot[19] = (kcat)*(y[18]);
 	 ydot[20] = (-(kdegS+(kon)*y[1]))*(y[20])+(-((kon)*y[0]))*(y[21])+(koff)*(y[22])+1.0;
 	 ydot[21] = (-((kon)*y[1]))*(y[20])+(-((kon)*y[0]))*(y[21])+(koff+kcat)*(y[22]);
 	 ydot[22] = ((kon)*y[1])*(y[20])+((kon)*y[0])*(y[21])+(-(koff+kcat))*(y[22]);
 	 ydot[23] = (kcat)*(y[22]);
 	 ydot[24] = (-(kdegS+(kon)*y[1]))*(y[24])+(-((kon)*y[0]))*(y[25])+(koff)*(y[26])-y[0];
 	 ydot[25] = (-((kon)*y[1]))*(y[24])+(-((kon)*y[0]))*(y[25])+(koff+kcat)*(y[26]);
 	 ydot[26] = ((kon)*y[1])*(y[24])+((kon)*y[0])*(y[25])+(-(koff+kcat))*(y[26]);
 	 ydot[27] = (kcat)*(y[26]);
 	 ydot[28] = (-(kdegS+(kon)*y[1]))*(y[28])+(-((kon)*y[0]))*(y[29])+(koff)*(y[30])-(y[1]*y[0]);
 	 ydot[29] = (-((kon)*y[1]))*(y[28])+(-((kon)*y[0]))*(y[29])+(koff+kcat)*(y[30])-(y[1]*y[0]);
 	 ydot[30] = ((kon)*y[1])*(y[28])+((kon)*y[0])*(y[29])+(-(koff+kcat))*(y[30])+y[1]*y[0];
 	 ydot[31] = (kcat)*(y[30]);
 	 ydot[32] = (-(kdegS+(kon)*y[1]))*(y[32])+(-((kon)*y[0]))*(y[33])+(koff)*(y[34])+y[2];
 	 ydot[33] = (-((kon)*y[1]))*(y[32])+(-((kon)*y[0]))*(y[33])+(koff+kcat)*(y[34])+y[2];
 	 ydot[34] = ((kon)*y[1])*(y[32])+((kon)*y[0])*(y[33])+(-(koff+kcat))*(y[34])-y[2];
 	 ydot[35] = (kcat)*(y[34]);
 	 ydot[36] = (-(kdegS+(kon)*y[1]))*(y[36])+(-((kon)*y[0]))*(y[37])+(koff)*(y[38]);
 	 ydot[37] = (-((kon)*y[1]))*(y[36])+(-((kon)*y[0]))*(y[37])+(koff+kcat)*(y[38])+y[2];
 	 ydot[38] = ((kon)*y[1])*(y[36])+((kon)*y[0])*(y[37])+(-(koff+kcat))*(y[38])-y[2];
 	 ydot[39] = (kcat)*(y[38])+y[2];
 	 ydot[40] = (-(kdegS+(kon)*y[1]))*(y[40])+(-((kon)*y[0]))*(y[41])+(koff)*(y[42]);
 	 ydot[41] = (-((kon)*y[1]))*(y[40])+(-((kon)*y[0]))*(y[41])+(koff+kcat)*(y[42]);
 	 ydot[42] = ((kon)*y[1])*(y[40])+((kon)*y[0])*(y[41])+(-(koff+kcat))*(y[42]);
 	 ydot[43] = (kcat)*(y[42]);

}

/** Event function **/
void petab_s_myevent(int *n, double *t, double *y) {

	 double time = *t;

	 if(*t == 0 & eventcounter[0] == 0) {
		y[5] = 0;
		y[9] = 0;
		y[13] = 0;
		y[17] = 0;
		y[21] = 0;
		y[25] = 0;
		y[29] = 0;
		y[33] = 0;
		y[37] = 0;
		y[41] = 0;
		y[41] = y[41] + 1.0;
		y[1] = Eadd;
		eventcounter[0] = eventcounter[0] + 1.;
	 }


}
