/** Code auto-generated by cOde 1.1.0 **/
#include <R.h> 
 #include <math.h> 

static double parms[90];
static double forc[0];
static double cons[0];
static double eventcounter[2];
static double range[2];

#define nGridpoints 2 
#define nSplines 0 
#define precision 1e-05 

#define ka parms[0] 
 #define Q1 parms[1] 
 #define Vc parms[2] 
 #define Vp1 parms[3] 
 #define CL parms[4] 
 #define GR parms[5] 
 #define EMAX parms[6] 
 #define eps parms[7] 
 #define hill parms[8] 
 #define EC50 parms[9] 
 #define y0_0 parms[10] 
 #define y1_0 parms[11] 
 #define y2_0 parms[12] 
 #define y3_0 parms[13] 
 #define y4_0 parms[14] 
 #define y5_0 parms[15] 
 #define y6_0 parms[16] 
 #define y7_0 parms[17] 
 #define y8_0 parms[18] 
 #define y9_0 parms[19] 
 #define y10_0 parms[20] 
 #define y11_0 parms[21] 
 #define y12_0 parms[22] 
 #define y13_0 parms[23] 
 #define y14_0 parms[24] 
 #define y15_0 parms[25] 
 #define y16_0 parms[26] 
 #define y17_0 parms[27] 
 #define y18_0 parms[28] 
 #define y19_0 parms[29] 
 #define y20_0 parms[30] 
 #define y21_0 parms[31] 
 #define y22_0 parms[32] 
 #define y23_0 parms[33] 
 #define y24_0 parms[34] 
 #define y25_0 parms[35] 
 #define y26_0 parms[36] 
 #define y27_0 parms[37] 
 #define y28_0 parms[38] 
 #define y29_0 parms[39] 
 #define y30_0 parms[40] 
 #define y31_0 parms[41] 
 #define y32_0 parms[42] 
 #define y33_0 parms[43] 
 #define y34_0 parms[44] 
 #define y35_0 parms[45] 
 #define y36_0 parms[46] 
 #define y37_0 parms[47] 
 #define y38_0 parms[48] 
 #define y39_0 parms[49] 
 #define y40_0 parms[50] 
 #define y41_0 parms[51] 
 #define y42_0 parms[52] 
 #define y43_0 parms[53] 
 #define y44_0 parms[54] 
 #define y45_0 parms[55] 
 #define y46_0 parms[56] 
 #define y47_0 parms[57] 
 #define y48_0 parms[58] 
 #define y49_0 parms[59] 
 #define y50_0 parms[60] 
 #define y51_0 parms[61] 
 #define y52_0 parms[62] 
 #define y53_0 parms[63] 
 #define y54_0 parms[64] 
 #define y55_0 parms[65] 
 #define y56_0 parms[66] 
 #define y57_0 parms[67] 
 #define y58_0 parms[68] 
 #define y59_0 parms[69] 
 #define y60_0 parms[70] 
 #define y61_0 parms[71] 
 #define y62_0 parms[72] 
 #define y63_0 parms[73] 
 #define y64_0 parms[74] 
 #define y65_0 parms[75] 
 #define y66_0 parms[76] 
 #define y67_0 parms[77] 
 #define y68_0 parms[78] 
 #define y69_0 parms[79] 
 #define y70_0 parms[80] 
 #define y71_0 parms[81] 
 #define y72_0 parms[82] 
 #define y73_0 parms[83] 
 #define y74_0 parms[84] 
 #define y75_0 parms[85] 
 #define y76_0 parms[86] 
 #define y77_0 parms[87] 
 #define y78_0 parms[88] 
 #define y79_0 parms[89] 
#define tmin range[0]
#define tmax range[1]


void MalariaMono_s_initmod(void (* odeparms)(int *, double *)) {
	 int N=90;
	 odeparms(&N, parms);
	 for(int i=0; i<2; ++i) eventcounter[i] = 0;
}

void MalariaMono_s_initforc(void (* odeforcs)(int *, double *)) {
	 int N=0;
	 odeforcs(&N, forc);
}

/** Derivatives (ODE system) **/
void MalariaMono_s_derivs (int *n, double *t, double *y, double *ydot, double *RPAR, int *IPAR) {

	 double time = *t;

	 ydot[0] = 1.0*(0.0);
 	 ydot[1] = 1.0*(y[0])-1.0*(ka*y[1]);
 	 ydot[2] = 1.0*(ka*y[1])-1.0*(Q1/Vc*y[2])+1.0*(Q1/Vp1*y[3])-1.0*(CL/Vc*y[2]);
 	 ydot[3] = 1.0*(Q1/Vc*y[2])-1.0*(Q1/Vp1*y[3]);
 	 ydot[4] = 1.0*(GR)-1.0*(EMAX*pow((y[2]/Vc+eps),hill)/(pow((y[2]/Vc+eps),hill)+pow(EC50,hill)));
 	 ydot[5] = 0;
 	 ydot[6] = (1.0)*(y[5])+(-ka)*(y[6]);
 	 ydot[7] = (ka)*(y[6])+(-(Q1/Vc+CL/Vc))*(y[7])+(Q1/Vp1)*(y[8]);
 	 ydot[8] = (Q1/Vc)*(y[7])+(-(Q1/Vp1))*(y[8]);
 	 ydot[9] = (-(EMAX*(pow((y[2]/Vc+eps),(hill-1.0))*(hill*(1.0/Vc)))/(pow((y[2]/Vc+eps),hill)+pow(EC50,hill))-EMAX*pow((y[2]/Vc+eps),hill)*(pow((y[2]/Vc+eps),(hill-1.0))*(hill*(1.0/Vc)))/pow((pow((y[2]/Vc+eps),hill)+pow(EC50,hill)),2.0)))*(y[7]);
 	 ydot[10] = 0;
 	 ydot[11] = (1.0)*(y[10])+(-ka)*(y[11]);
 	 ydot[12] = (ka)*(y[11])+(-(Q1/Vc+CL/Vc))*(y[12])+(Q1/Vp1)*(y[13]);
 	 ydot[13] = (Q1/Vc)*(y[12])+(-(Q1/Vp1))*(y[13]);
 	 ydot[14] = (-(EMAX*(pow((y[2]/Vc+eps),(hill-1.0))*(hill*(1.0/Vc)))/(pow((y[2]/Vc+eps),hill)+pow(EC50,hill))-EMAX*pow((y[2]/Vc+eps),hill)*(pow((y[2]/Vc+eps),(hill-1.0))*(hill*(1.0/Vc)))/pow((pow((y[2]/Vc+eps),hill)+pow(EC50,hill)),2.0)))*(y[12]);
 	 ydot[15] = 0;
 	 ydot[16] = (1.0)*(y[15])+(-ka)*(y[16]);
 	 ydot[17] = (ka)*(y[16])+(-(Q1/Vc+CL/Vc))*(y[17])+(Q1/Vp1)*(y[18]);
 	 ydot[18] = (Q1/Vc)*(y[17])+(-(Q1/Vp1))*(y[18]);
 	 ydot[19] = (-(EMAX*(pow((y[2]/Vc+eps),(hill-1.0))*(hill*(1.0/Vc)))/(pow((y[2]/Vc+eps),hill)+pow(EC50,hill))-EMAX*pow((y[2]/Vc+eps),hill)*(pow((y[2]/Vc+eps),(hill-1.0))*(hill*(1.0/Vc)))/pow((pow((y[2]/Vc+eps),hill)+pow(EC50,hill)),2.0)))*(y[17]);
 	 ydot[20] = 0;
 	 ydot[21] = (1.0)*(y[20])+(-ka)*(y[21]);
 	 ydot[22] = (ka)*(y[21])+(-(Q1/Vc+CL/Vc))*(y[22])+(Q1/Vp1)*(y[23]);
 	 ydot[23] = (Q1/Vc)*(y[22])+(-(Q1/Vp1))*(y[23]);
 	 ydot[24] = (-(EMAX*(pow((y[2]/Vc+eps),(hill-1.0))*(hill*(1.0/Vc)))/(pow((y[2]/Vc+eps),hill)+pow(EC50,hill))-EMAX*pow((y[2]/Vc+eps),hill)*(pow((y[2]/Vc+eps),(hill-1.0))*(hill*(1.0/Vc)))/pow((pow((y[2]/Vc+eps),hill)+pow(EC50,hill)),2.0)))*(y[22]);
 	 ydot[25] = 0;
 	 ydot[26] = (1.0)*(y[25])+(-ka)*(y[26]);
 	 ydot[27] = (ka)*(y[26])+(-(Q1/Vc+CL/Vc))*(y[27])+(Q1/Vp1)*(y[28]);
 	 ydot[28] = (Q1/Vc)*(y[27])+(-(Q1/Vp1))*(y[28]);
 	 ydot[29] = (-(EMAX*(pow((y[2]/Vc+eps),(hill-1.0))*(hill*(1.0/Vc)))/(pow((y[2]/Vc+eps),hill)+pow(EC50,hill))-EMAX*pow((y[2]/Vc+eps),hill)*(pow((y[2]/Vc+eps),(hill-1.0))*(hill*(1.0/Vc)))/pow((pow((y[2]/Vc+eps),hill)+pow(EC50,hill)),2.0)))*(y[27]);
 	 ydot[30] = 0;
 	 ydot[31] = (1.0)*(y[30])+(-ka)*(y[31])-y[1];
 	 ydot[32] = (ka)*(y[31])+(-(Q1/Vc+CL/Vc))*(y[32])+(Q1/Vp1)*(y[33])+y[1];
 	 ydot[33] = (Q1/Vc)*(y[32])+(-(Q1/Vp1))*(y[33]);
 	 ydot[34] = (-(EMAX*(pow((y[2]/Vc+eps),(hill-1.0))*(hill*(1.0/Vc)))/(pow((y[2]/Vc+eps),hill)+pow(EC50,hill))-EMAX*pow((y[2]/Vc+eps),hill)*(pow((y[2]/Vc+eps),(hill-1.0))*(hill*(1.0/Vc)))/pow((pow((y[2]/Vc+eps),hill)+pow(EC50,hill)),2.0)))*(y[32]);
 	 ydot[35] = 0;
 	 ydot[36] = (1.0)*(y[35])+(-ka)*(y[36]);
 	 ydot[37] = (ka)*(y[36])+(-(Q1/Vc+CL/Vc))*(y[37])+(Q1/Vp1)*(y[38])+1.0/Vp1*y[3]-1.0/Vc*y[2];
 	 ydot[38] = (Q1/Vc)*(y[37])+(-(Q1/Vp1))*(y[38])+1.0/Vc*y[2]-1.0/Vp1*y[3];
 	 ydot[39] = (-(EMAX*(pow((y[2]/Vc+eps),(hill-1.0))*(hill*(1.0/Vc)))/(pow((y[2]/Vc+eps),hill)+pow(EC50,hill))-EMAX*pow((y[2]/Vc+eps),hill)*(pow((y[2]/Vc+eps),(hill-1.0))*(hill*(1.0/Vc)))/pow((pow((y[2]/Vc+eps),hill)+pow(EC50,hill)),2.0)))*(y[37]);
 	 ydot[40] = 0;
 	 ydot[41] = (1.0)*(y[40])+(-ka)*(y[41]);
 	 ydot[42] = (ka)*(y[41])+(-(Q1/Vc+CL/Vc))*(y[42])+(Q1/Vp1)*(y[43])+Q1/pow(Vc,2.0)*y[2]+CL/pow(Vc,2.0)*y[2];
 	 ydot[43] = (Q1/Vc)*(y[42])+(-(Q1/Vp1))*(y[43])-(Q1/pow(Vc,2.0)*y[2]);
 	 ydot[44] = (-(EMAX*(pow((y[2]/Vc+eps),(hill-1.0))*(hill*(1.0/Vc)))/(pow((y[2]/Vc+eps),hill)+pow(EC50,hill))-EMAX*pow((y[2]/Vc+eps),hill)*(pow((y[2]/Vc+eps),(hill-1.0))*(hill*(1.0/Vc)))/pow((pow((y[2]/Vc+eps),hill)+pow(EC50,hill)),2.0)))*(y[42])+EMAX*(pow((y[2]/Vc+eps),(hill-1.0))*(hill*(y[2]/pow(Vc,2.0))))/(pow((y[2]/Vc+eps),hill)+pow(EC50,hill))-EMAX*pow((y[2]/Vc+eps),hill)*(pow((y[2]/Vc+eps),(hill-1.0))*(hill*(y[2]/pow(Vc,2.0))))/pow((pow((y[2]/Vc+eps),hill)+pow(EC50,hill)),2.0);
 	 ydot[45] = 0;
 	 ydot[46] = (1.0)*(y[45])+(-ka)*(y[46]);
 	 ydot[47] = (ka)*(y[46])+(-(Q1/Vc+CL/Vc))*(y[47])+(Q1/Vp1)*(y[48])-(Q1/pow(Vp1,2.0)*y[3]);
 	 ydot[48] = (Q1/Vc)*(y[47])+(-(Q1/Vp1))*(y[48])+Q1/pow(Vp1,2.0)*y[3];
 	 ydot[49] = (-(EMAX*(pow((y[2]/Vc+eps),(hill-1.0))*(hill*(1.0/Vc)))/(pow((y[2]/Vc+eps),hill)+pow(EC50,hill))-EMAX*pow((y[2]/Vc+eps),hill)*(pow((y[2]/Vc+eps),(hill-1.0))*(hill*(1.0/Vc)))/pow((pow((y[2]/Vc+eps),hill)+pow(EC50,hill)),2.0)))*(y[47]);
 	 ydot[50] = 0;
 	 ydot[51] = (1.0)*(y[50])+(-ka)*(y[51]);
 	 ydot[52] = (ka)*(y[51])+(-(Q1/Vc+CL/Vc))*(y[52])+(Q1/Vp1)*(y[53])-(1.0/Vc*y[2]);
 	 ydot[53] = (Q1/Vc)*(y[52])+(-(Q1/Vp1))*(y[53]);
 	 ydot[54] = (-(EMAX*(pow((y[2]/Vc+eps),(hill-1.0))*(hill*(1.0/Vc)))/(pow((y[2]/Vc+eps),hill)+pow(EC50,hill))-EMAX*pow((y[2]/Vc+eps),hill)*(pow((y[2]/Vc+eps),(hill-1.0))*(hill*(1.0/Vc)))/pow((pow((y[2]/Vc+eps),hill)+pow(EC50,hill)),2.0)))*(y[52]);
 	 ydot[55] = 0;
 	 ydot[56] = (1.0)*(y[55])+(-ka)*(y[56]);
 	 ydot[57] = (ka)*(y[56])+(-(Q1/Vc+CL/Vc))*(y[57])+(Q1/Vp1)*(y[58]);
 	 ydot[58] = (Q1/Vc)*(y[57])+(-(Q1/Vp1))*(y[58]);
 	 ydot[59] = (-(EMAX*(pow((y[2]/Vc+eps),(hill-1.0))*(hill*(1.0/Vc)))/(pow((y[2]/Vc+eps),hill)+pow(EC50,hill))-EMAX*pow((y[2]/Vc+eps),hill)*(pow((y[2]/Vc+eps),(hill-1.0))*(hill*(1.0/Vc)))/pow((pow((y[2]/Vc+eps),hill)+pow(EC50,hill)),2.0)))*(y[57])+1.0;
 	 ydot[60] = 0;
 	 ydot[61] = (1.0)*(y[60])+(-ka)*(y[61]);
 	 ydot[62] = (ka)*(y[61])+(-(Q1/Vc+CL/Vc))*(y[62])+(Q1/Vp1)*(y[63]);
 	 ydot[63] = (Q1/Vc)*(y[62])+(-(Q1/Vp1))*(y[63]);
 	 ydot[64] = (-(EMAX*(pow((y[2]/Vc+eps),(hill-1.0))*(hill*(1.0/Vc)))/(pow((y[2]/Vc+eps),hill)+pow(EC50,hill))-EMAX*pow((y[2]/Vc+eps),hill)*(pow((y[2]/Vc+eps),(hill-1.0))*(hill*(1.0/Vc)))/pow((pow((y[2]/Vc+eps),hill)+pow(EC50,hill)),2.0)))*(y[62])-(pow((y[2]/Vc+eps),hill)/(pow((y[2]/Vc+eps),hill)+pow(EC50,hill)));
 	 ydot[65] = 0;
 	 ydot[66] = (1.0)*(y[65])+(-ka)*(y[66]);
 	 ydot[67] = (ka)*(y[66])+(-(Q1/Vc+CL/Vc))*(y[67])+(Q1/Vp1)*(y[68]);
 	 ydot[68] = (Q1/Vc)*(y[67])+(-(Q1/Vp1))*(y[68]);
 	 ydot[69] = (-(EMAX*(pow((y[2]/Vc+eps),(hill-1.0))*(hill*(1.0/Vc)))/(pow((y[2]/Vc+eps),hill)+pow(EC50,hill))-EMAX*pow((y[2]/Vc+eps),hill)*(pow((y[2]/Vc+eps),(hill-1.0))*(hill*(1.0/Vc)))/pow((pow((y[2]/Vc+eps),hill)+pow(EC50,hill)),2.0)))*(y[67])-(EMAX*(pow((y[2]/Vc+eps),(hill-1.0))*hill)/(pow((y[2]/Vc+eps),hill)+pow(EC50,hill))-EMAX*pow((y[2]/Vc+eps),hill)*(pow((y[2]/Vc+eps),(hill-1.0))*hill)/pow((pow((y[2]/Vc+eps),hill)+pow(EC50,hill)),2.0));
 	 ydot[70] = 0;
 	 ydot[71] = (1.0)*(y[70])+(-ka)*(y[71]);
 	 ydot[72] = (ka)*(y[71])+(-(Q1/Vc+CL/Vc))*(y[72])+(Q1/Vp1)*(y[73]);
 	 ydot[73] = (Q1/Vc)*(y[72])+(-(Q1/Vp1))*(y[73]);
 	 ydot[74] = (-(EMAX*(pow((y[2]/Vc+eps),(hill-1.0))*(hill*(1.0/Vc)))/(pow((y[2]/Vc+eps),hill)+pow(EC50,hill))-EMAX*pow((y[2]/Vc+eps),hill)*(pow((y[2]/Vc+eps),(hill-1.0))*(hill*(1.0/Vc)))/pow((pow((y[2]/Vc+eps),hill)+pow(EC50,hill)),2.0)))*(y[72])-(EMAX*(pow((y[2]/Vc+eps),hill)*log((y[2]/Vc+eps)))/(pow((y[2]/Vc+eps),hill)+pow(EC50,hill))-EMAX*pow((y[2]/Vc+eps),hill)*(pow((y[2]/Vc+eps),hill)*log((y[2]/Vc+eps))+pow(EC50,hill)*log(EC50))/pow((pow((y[2]/Vc+eps),hill)+pow(EC50,hill)),2.0));
 	 ydot[75] = 0;
 	 ydot[76] = (1.0)*(y[75])+(-ka)*(y[76]);
 	 ydot[77] = (ka)*(y[76])+(-(Q1/Vc+CL/Vc))*(y[77])+(Q1/Vp1)*(y[78]);
 	 ydot[78] = (Q1/Vc)*(y[77])+(-(Q1/Vp1))*(y[78]);
 	 ydot[79] = (-(EMAX*(pow((y[2]/Vc+eps),(hill-1.0))*(hill*(1.0/Vc)))/(pow((y[2]/Vc+eps),hill)+pow(EC50,hill))-EMAX*pow((y[2]/Vc+eps),hill)*(pow((y[2]/Vc+eps),(hill-1.0))*(hill*(1.0/Vc)))/pow((pow((y[2]/Vc+eps),hill)+pow(EC50,hill)),2.0)))*(y[77])+EMAX*pow((y[2]/Vc+eps),hill)*(pow(EC50,(hill-1.0))*hill)/pow((pow((y[2]/Vc+eps),hill)+pow(EC50,hill)),2.0);

}

/** Event function **/
void MalariaMono_s_myevent(int *n, double *t, double *y) {

	 double time = *t;

	 if(*t == 0 & eventcounter[0] == 0) {
		y[5] = 0;
		y[10] = 0;
		y[15] = 0;
		y[20] = 0;
		y[25] = 0;
		y[30] = 0;
		y[35] = 0;
		y[40] = 0;
		y[45] = 0;
		y[50] = 0;
		y[55] = 0;
		y[60] = 0;
		y[65] = 0;
		y[70] = 0;
		y[75] = 0;
		y[0] = 6e+06;
		eventcounter[0] = eventcounter[0] + 1.;
	 }

	 if(*t == 1e-04 & eventcounter[1] == 0) {
		y[5] = 0;
		y[10] = 0;
		y[15] = 0;
		y[20] = 0;
		y[25] = 0;
		y[30] = 0;
		y[35] = 0;
		y[40] = 0;
		y[45] = 0;
		y[50] = 0;
		y[55] = 0;
		y[60] = 0;
		y[65] = 0;
		y[70] = 0;
		y[75] = 0;
		y[0] = 0;
		eventcounter[1] = eventcounter[1] + 1.;
	 }


}
