/** Code auto-generated by cOde 1.1.0 **/
#include <R.h> 
 #include <math.h> 

static double parms[15];
static double forc[0];
static double cons[0];
static double eventcounter[2];
static double range[2];

#define nGridpoints 2 
#define nSplines 0 
#define precision 1e-05 

#define ka parms[0] 
 #define Q1 parms[1] 
 #define Vc parms[2] 
 #define Vp1 parms[3] 
 #define CL parms[4] 
 #define GR parms[5] 
 #define EMAX parms[6] 
 #define eps parms[7] 
 #define hill parms[8] 
 #define EC50 parms[9] 
 #define y0_0 parms[10] 
 #define y1_0 parms[11] 
 #define y2_0 parms[12] 
 #define y3_0 parms[13] 
 #define y4_0 parms[14] 
#define tmin range[0]
#define tmax range[1]


void MalariaMono_initmod(void (* odeparms)(int *, double *)) {
	 int N=15;
	 odeparms(&N, parms);
	 for(int i=0; i<2; ++i) eventcounter[i] = 0;
}

void MalariaMono_initforc(void (* odeforcs)(int *, double *)) {
	 int N=0;
	 odeforcs(&N, forc);
}

/** Derivatives (ODE system) **/
void MalariaMono_derivs (int *n, double *t, double *y, double *ydot, double *RPAR, int *IPAR) {

	 double time = *t;

	 ydot[0] = 1.0*(0.0);
 	 ydot[1] = 1.0*(y[0])-1.0*(ka*y[1]);
 	 ydot[2] = 1.0*(ka*y[1])-1.0*(Q1/Vc*y[2])+1.0*(Q1/Vp1*y[3])-1.0*(CL/Vc*y[2]);
 	 ydot[3] = 1.0*(Q1/Vc*y[2])-1.0*(Q1/Vp1*y[3]);
 	 ydot[4] = 1.0*(GR)-1.0*(EMAX*pow((y[2]/Vc+eps),hill)/(pow((y[2]/Vc+eps),hill)+pow(EC50,hill)));

}

/** Event function **/
void MalariaMono_myevent(int *n, double *t, double *y) {

	 double time = *t;

	 if(*t == 0 & eventcounter[0] == 0) {
		y[0] = 6e+06;
		eventcounter[0] = eventcounter[0] + 1.;
	 }

	 if(*t == 1e-04 & eventcounter[1] == 0) {
		y[0] = 0;
		eventcounter[1] = eventcounter[1] + 1.;
	 }


}
